const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');const files=['vendor/majiang.js','engine.js','taiwan.js','match.js','japanese.js','yaku.js','victory.js','enhance.js','quiz-bank.js','discard-challenges.js','experience.js','review.js','history.js','app.js'];const src=files.map(f=>fs.readFileSync('dist/'+f,'utf8')).join('\n');const c={Date,console,localStorage:{getItem:()=>null},setTimeout(){},clearTimeout(){}};vm.createContext(c);vm.runInContext(src.slice(0,src.indexOf("$('#settings').onclick="))+'\nrender=()=>{};',c);const run=s=>vm.runInContext(s,c);
run("start();g.turn=0;g.phase='discard';before=g.h[0].length;first=g.h[0][0];clickHandTile(0)");assert.equal(run('g.h[0].length'),run('before-1'));assert.equal(run('g.river.at(-1).t'),run('first'));run('clickHandTile(0)');assert.equal(run('g.h[0].length'),run('before-1'));
run("start();g.turn=1;before=g.h[0].length;clickHandTile(0)");assert.equal(run('g.h[0].length'),run('before'));
run("cfg.mode='jp';start();g.h[0]=[0,1,2,3,4,5,9,10,11,18,19,20,27,28];g.drawn[0]=28;riichiPicking=true;i=riichiDiscards(0)[0];clickHandTile(i)");assert.equal(run('g.riichi[0]'),true);assert.equal(run('g.scores[0]'),24000);assert.equal(run('riichiPicking'),false);
assert.deepEqual(Array.from(run('[3,4,7,8,15,16].map(n=>victoryTier({tw:{payments:[{tai:n}]}}))')),[0,1,1,2,2,3]);
run("cfg.mode='tw';start();g.h[0]=[0,0,0,3,3,3,9,9,9,18,18,18,22,22,22,27,27];g.drawn[0]=27;won(0,true)");const html=run('victoryMarkup(g.victory)');assert.match(html,/<ul class="score-items">/);assert.ok(html.indexOf('五暗刻')<html.indexOf('台型合計'));assert.match(html,/莊家/);assert.match(html,/共收/);
// Inspect only the explicitly visible tile DOM nodes.
let matches=[];c.document={querySelectorAll:s=>{assert.equal(s,'.table .river .tile,.table .exposed .tile');return [0,3,0].map(t=>({dataset:{tile:String(t)},classList:{toggle(k,on){matches.push(on)}}}))},querySelector:()=>({textContent:''})};run('g.end="";previewHandTile(0)');assert.deepEqual(matches,[true,false,true]);
let spoken=[];c.window={SpeechSynthesisUtterance:class{constructor(t){this.text=t}},speechSynthesis:{getVoices:()=>[{lang:'zh-TW'}],cancel(){},speak(u){spoken.push(u.text)}}};run("speechUnlocked=true;cfg.voice=true;cfg.sound=true;cfg.voicePack='auto';speakGameEvent('碰')");assert.equal(spoken.length,0);run("cfg.voicePack='tw';speakGameEvent('胡牌')");assert.ok(spoken[0].includes('台'));run("cfg.voice=false;speakGameEvent('碰')");assert.equal(spoken.length,1);
console.log('PASS: immediate single discard, turn guard, riichi click flow, visible-only matching, itemized totals, tier thresholds, recorded-pack isolation and Chinese voice mute.');
