const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');const src=['vendor/majiang.js','engine.js','taiwan.js','match.js','japanese.js','yaku.js','victory.js','enhance.js','quiz-bank.js','discard-challenges.js','experience.js','review.js','history.js','app.js'].map(f=>fs.readFileSync('dist/'+f,'utf8')).join('\n');let pending=0;const ctx={Date,console,setTimeout:()=>++pending,clearTimeout:()=>{pending=0},localStorage:{getItem:()=>null}};vm.createContext(ctx);vm.runInContext(src.slice(0,src.indexOf("$('#settings').onclick="))+'\nrender=()=>{};',ctx);const run=s=>vm.runInContext(s,ctx);
run(`function fixture(seven=false,eight=false){cfg.mode='tw';cfg.matchLength='east';cfg.tw=twDefaults();cfg.tw.enabled.sevenFlowers=seven;cfg.tw.enabled.eightFlowers=eight;start();g.flowerTiles=[[],[],[],[]];g.flowers=[0,0,0,0];g.h=[[],[],[],[]];g.m=[[],[],[],[]];g.mcore=[[],[],[],[]];g.drawn.fill(null);g.wall=[0];g.river=[];g.dealer=0;g.repeatCount=0}function give(p,ts){g.flowerTiles[p]=ts;g.flowers[p]=ts.length}`);
assert.equal(run('twNormalize({}).enabled.sevenFlowers'),false);assert.equal(run('twNormalize({}).enabled.eightFlowers'),false);
// Seventh flower drawn while eighth is already exposed: win without drawing replacement.
run("fixture(true,false);give(1,[34,35,36,37,38,39]);give(2,[41]);g.wall=[0,40];draw(1)");assert.equal(run('g.victory.special'),'sevenFlowers');assert.equal(run('g.victory.player'),1);assert.equal(run('g.victory.from'),2);assert.equal(run('g.wall.length'),1);assert.equal(run('g.h[1].length'),0);assert.equal(run('g.scores.reduce((a,b)=>a+b,0)'),100000);assert.deepEqual(Array.from(run('g.flowerTiles.map(a=>a.length)')),[0,7,1,0]);assert.equal(run('g.victory.tw.items.length'),1);assert.equal(run('g.victory.tw.payments.length'),1);assert.match(run('victoryMarkup(g.victory)'),/七搶一/);assert.ok(!run('victoryMarkup(g.victory)').includes('undefined'));const before=run('g.scores.join()');run("twCheckFlowerWin();draw(1);won(1,true);finish('overwrite');afterDiscard(1,0)");assert.equal(run('g.scores.join()'),before);assert.match(run('g.end'),/七搶一/);assert.equal(pending,0);
// Eighth flower drawn by another player, including the last wall tile.
run("fixture(true,false);give(3,[34,35,36,37,38,39,40]);g.wall=[41];draw(0)");assert.equal(run('g.victory.player'),3);assert.equal(run('g.victory.from'),0);assert.match(run('g.end'),/七搶一/);
// Seven alone does not win; switches are independent; no-flower and JP modes ignore both.
run("fixture(true,false);give(1,[34,35,36,37,38,39,40]);twCheckFlowerWin()");assert.equal(run('g.end'),'');
run("fixture(false,true);give(1,[34,35,36,37,38,39,40]);give(0,[41]);twCheckFlowerWin()");assert.equal(run('g.end'),'');
run("fixture(true,false);give(1,[34,35,36,37,38,39,40,41]);twCheckFlowerWin()");assert.equal(run('g.end'),'');
for(const mode of ['jp','tw']){run(`fixture(true,true);give(0,[34,35,36,37,38,39,40,41]);g.rules.mode='${mode}';g.rules.flowers=false;twCheckFlowerWin()`);assert.equal(run('g.end'),'')}
// Eight-flower self collection: all three payments, capped custom score, no ordinary bonuses.
run("fixture(false,true);give(0,[34,35,36,37,38,39,40]);g.rules.tw.values.eightFlowers=16;g.rules.tw.cap=10;g.wall=[41];draw(0)");assert.equal(run('g.victory.special'),'eightFlowers');assert.equal(run('g.victory.tai'),16);assert.equal(run('g.victory.tw.items.length'),1);assert.deepEqual(Array.from(run('g.victory.tw.payments.map(x=>x.money)')),[300,300,300]);assert.equal(run('matchState.repeats'),1);assert.match(run('victoryMarkup(g.victory)'),/八仙過海/);
// Zero tai is still enabled, and seven-flower special overrides ordinary self-draw-only rule.
run("fixture(true,false);give(0,[34,35,36,37,38,39,40]);give(1,[41]);g.rules.self=true;g.rules.tw.values.sevenFlowers=0;twCheckFlowerWin()");assert.equal(run('g.victory.tai'),0);
// Initial deal defers checks until all four hands have been dealt, then stops before extra draw.
run("cfg.tw=twDefaults();cfg.tw.enabled.eightFlowers=true;oldShuffle=shuffle;shuffle=a=>{let flowers=a.filter(t=>t>=34),normal=a.filter(t=>t<34);return [...normal,...flowers]};start();shuffle=oldShuffle");assert.equal(run('g.victory.special'),'eightFlowers');assert.deepEqual(Array.from(run('g.h.map(h=>h.length)')),[16,16,16,16]);assert.equal(run('g.dealing'),false);assert.equal(run('g.h.flat().length+g.flowerTiles.flat().length+g.wall.length'),144);assert.equal(pending,0);
// Default closed switches preserve normal draw / flower replacement flow.
run("fixture();give(1,[34,35,36,37,38,39,40]);g.wall=[0,41];draw(1)");assert.equal(run('g.end'),'');assert.equal(run('g.drawn[1]'),0);
console.log('PASS: flower switches, both seven-one arrival orders, eight flowers, replacement interruption, last wall tile, initial deal, zero-tai trigger, scoring, conservation, and idempotent settlement.');
